spring:
  application:
    name: Api Request Test
  server:
    port: 8080
  swagger:
    enabled: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  messages:
    basename: messages
    encoding: UTF-8
  web:
    locale: es_PY
  
    
